/**:
  ros__parameters:
    joint_initial_positions: [0.0, 0.85148, 1.45637] # [hipAA, hipFE, kneeFE]
    # joint_initial_positions: [0.0, 0.0, 1.57079632679 ] # [hipAA, hipFE, kneeFE]
    link_lengths: [0.12036888, 0.3705942, 0.36328592] # [hipAA, hipFE, kneeFE]
